[template]
exclude = ["cliff.toml"]

[placeholders.author]
type = "string"
prompt = "Enter your name"
default = "Aizen"

[placeholders.license]
type = "string"
prompt = "Enter project lincese"
default = "MIT"


[template.post-hook]
run = "pre-commit install"
